version: "3"

services:
  caddy-service:
    image: localhost/caddy
    container_name: "caddy-service"
    build:
      context: $PWD/caddy
      dockerfile: $PWD/caddy/caddy.dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/data:/data
    deploy:
      mode: replicated
      replicas: 1

  coredns-service:
    image: localhost/coredns
    container_name: "coredns-service"
    build: 
      context: $PWD/coredns
      dockerfile: $PWD/coredns/coredns.dockerfile
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
